### ISSUE TITLE
docs: Make the available endpoints documentation more specific

### ISSUE THREAD

**Issue by garrettkmoody** [garrettkmoody/WWU-Wash-And-Dry-Backend#15]
There should be specific expected JSON objects and status codes for each endpoint. There should also be expected JSON responses for failed requests.

**Comment by haydentinker** [comment]
I just updated some of the endpoints documentation and submitted a pr let me know if that will work. If not I can go back and add more information.

**Comment by haydentinker** [comment]
I just added some validation to the put and post machine endpoints. Once that pull request gets merged, we will need to update our documentation so reflect the changes.

**Comment by TaylorSmith28** [comment]
This issue is closed with Hayden's last pull request.
